version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Canada/Montreal
    ports:
      - 5055:5055
    volumes:
      - ./config:/app/config
    restart: unless-stopped
