version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "./data:/data"
      - "/path/to/Music:/music:ro"
