version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --http-api-metrics --http-api-token <device_name>
    ports:
      - 8080:8080
